#!/bin/bash
set -e

function green() {
  echo -e "\e[32m$1\e[0m"
}

# obtain the last non-root user; assuming that may be the sole user of the motd
USER=$(last | grep "logged in" | grep -o '^\S*')

# prompt the user for preferences
green "Do you want the MOTD to display for all users, or just $USER?\nEnter your choice by supplying the number only:\n\t1 = $USER only\n\t2 = All users"
read -r CHOICE

if [ "$CHOICE" == '1' ];
then

  # remove any residual config
  echo "Removing old config for global users (if exists)..."
  sed -i '/# displays motd/,/simple-motd>/d' /home/*/.bashrc

  echo "Setting config for $USER..."
  echo "# displays motd from https://github.com/angela-d/simple-motd-for-debian-desktop" >> /home/"$USER"/.bashrc
  echo "simple-motd" >> /home/"$USER"/.bashrc
  echo "Done."

else

  echo "# displays motd from https://github.com/angela-d/simple-motd-for-debian-desktop" >> /home/*/.bashrc
  echo "simple-motd" >> /home/*/.bashrc
  green "MOTD has been set up globally.\n To take effect, open a new terminal, or run:\n\t. ~/.bashrc"

fi
