.de EX
.ne 5
.if n .sp 1
.if t .sp .5
.nf
.in +.5i
..
.de EE
.fi
.in -.5i
.if n .sp 1
.if t .sp .5
..
.TH simple-motd 1 "May 16, 2019"
.SH NAME
Simple MOTD \- Prettify your terminal with ascii art and informative data about your system.
.SH SYNOPSIS
.B simple-motd
.PP
Liven up a terminal window on first launch.
.SH DESCRIPTION
No config necessary - works out of the box!
.PP
If you wish to change your user options at any time:
.SS "Command reference:"
.TP
\fBdpkg-reconfigure simple-motd\fR
Re-initialize post-install prompt to place MOTD in one user or global user displays.
.TP
.SH SEE ALSO
None
.SH BUGS
See/report bugs at https://github.com/angela-d/simple-motd-for-debian-desktop
.SH AUTHOR
The text for this page was written by Angela <angelad@disroot.org> for the Debian GNU/Linux system (but may be used by
others).
.SH COPYRIGHT
Copyright  (C) 2018 Angela.  License GPLv3: GNU
GPL version 3 only <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
