#!/bin/bash
set -e

# cleanup bashrc references to simple-motd, so errors aren't triggered after simple-motd is uninstalled
sed -i '/# displays motd/,/source \/etc\/profile.d\/simple-motd/d' /etc/bash.bashrc
